service: hamish-portfolio

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  memorySize: 128

functions:
  headers:
    handler: headers.handler
    events:
      - cloudFront:
          eventType: origin-response
          origin: https://d39w4n5rrkxzvy.cloudfront.net
  api:
    handler: index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
